# Generated by Django 2.1.7 on 2019-03-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(default='English', help_text='Enter a language if not in English', max_length=200),
        ),
    ]
