# Generated by Django 2.1.7 on 2019-03-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190314_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='English', help_text='Enter a language if not in English', max_length=200),
        ),
    ]
