# Generated by Django 2.1.7 on 2019-03-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190320_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.CharField(default='book-generic.jpg', max_length=250),
            preserve_default=False,
        ),
    ]
